In [1]:
import pandas as pd
import numpy as np
import scipy.stats as sp
import altair as alt
import geopandas as gpd

from vega_datasets import data

In [9]:
# counties = data/us-10m.json

counties = alt.topo_feature(data.us_10m.url, feature='counties')
background = alt.Chart(counties).mark_geoshape(
    fill='lightgray',
    stroke='white'
).project('albersUsa')

background

alt.Chart(...)

In [2]:
counties = gpd.read_file('https://gist.githubusercontent.com/sdwfrost/d1c73f91dd9d175998ed166eb216994a/raw/e89c35f308cee7e2e5a784e1d3afc5d449e9e4bb/counties.geojson')
counties_zip = pd.read_csv('https://raw.githubusercontent.com/scpike/us-state-county-zip/master/geo-data.csv')

In [3]:
counties['state_fips'] = counties['STATEFP'].astype('int')
counties

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry,state_fips
0,06,075,00277302,0500000US06075,06075,San Francisco,06,121485107,479107241,"POLYGON ((-122.51198 37.77113, -122.46540 37.8...",6
1,25,025,00606939,0500000US25025,25025,Suffolk,06,150855462,160479920,"POLYGON ((-71.19115 42.28306, -71.15689 42.330...",25
2,31,007,00835826,0500000US31007,31007,Banner,06,1932676697,397069,"POLYGON ((-104.05283 41.69795, -103.37039 41.6...",31
3,37,181,01008591,0500000US37181,37181,Vance,06,653705784,42187365,"POLYGON ((-78.49778 36.51448, -78.45728 36.541...",37
4,48,421,01383996,0500000US48421,48421,Sherman,06,2390651189,428754,"POLYGON ((-102.16246 36.50033, -102.03234 36.5...",48
...,...,...,...,...,...,...,...,...,...,...,...
3215,29,163,00758536,0500000US29163,29163,Pike,06,1736428536,36976453,"POLYGON ((-91.46044 39.45072, -91.18288 39.598...",29
3216,72,001,01804480,0500000US72001,72001,Adjuntas,13,172725728,1051790,"POLYGON ((-66.83274 18.22799, -66.81727 18.230...",72
3217,19,079,00465228,0500000US19079,19079,Hamilton,06,1493777024,1965341,"POLYGON ((-93.97158 42.55814, -93.49949 42.557...",19
3218,19,027,00465203,0500000US19027,19027,Carroll,06,1474835092,2145349,"POLYGON ((-95.09085 42.21040, -94.85841 42.209...",19
3219,13,073,00348865,0500000US13073,13073,Columbia,06,751323672,45373097,"POLYGON ((-82.42533 33.65063, -82.30825 33.700...",13

In [5]:
counties_zip['NAME'] = counties_zip['county']
counties_zip

,state_fips,state,state_abbr,zipcode,county,city,NAME
0,1,Alabama,AL,35004,St. Clair,Acmar,St. Clair
1,1,Alabama,AL,35005,Jefferson,Adamsville,Jefferson
2,1,Alabama,AL,35006,Jefferson,Adger,Jefferson
3,1,Alabama,AL,35007,Shelby,Keystone,Shelby
4,1,Alabama,AL,35010,Tallapoosa,New site,Tallapoosa
...,...,...,...,...,...,...,...
33098,56,Wyoming,WY,83126,Lincoln,Smoot,Lincoln
33099,56,Wyoming,WY,83127,Lincoln,Thayne,Lincoln
33100,56,Wyoming,WY,83128,Lincoln,Alpine,Lincoln
33101,56,Wyoming,WY,831HH,Lincoln,Zcta 831hh,Lincoln
33102,56,Wyoming,WY,831XX,Lincoln,Zcta 831xx,Lincoln

In [6]:
counties.merge(counties_zip[['state_fips', 'zipcode', 'NAME']], on=['state_fips', 'NAME'], how='left')

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry,state_fips,zipcode
0,06,075,00277302,0500000US06075,06075,San Francisco,06,121485107,479107241,"POLYGON ((-122.51198 37.77113, -122.46540 37.8...",6,94102
1,06,075,00277302,0500000US06075,06075,San Francisco,06,121485107,479107241,"POLYGON ((-122.51198 37.77113, -122.46540 37.8...",6,94103
2,06,075,00277302,0500000US06075,06075,San Francisco,06,121485107,479107241,"POLYGON ((-122.51198 37.77113, -122.46540 37.8...",6,94104
3,06,075,00277302,0500000US06075,06075,San Francisco,06,121485107,479107241,"POLYGON ((-122.51198 37.77113, -122.46540 37.8...",6,94105
4,06,075,00277302,0500000US06075,06075,San Francisco,06,121485107,479107241,"POLYGON ((-122.51198 37.77113, -122.46540 37.8...",6,94107
...,...,...,...,...,...,...,...,...,...,...,...,...
32343,13,073,00348865,0500000US13073,13073,Columbia,06,751323672,45373097,"POLYGON ((-82.42533 33.65063, -82.30825 33.700...",13,30809
32344,13,073,00348865,0500000US13073,13073,Columbia,06,751323672,45373097,"POLYGON ((-82.42533 33.65063, -82.30825 33.700...",13,30813
32345,13,073,00348865,0500000US13073,13073,Columbia,06,751323672,45373097,"POLYGON ((-82.42533 33.65063, -82.30825 33.700...",13,30814
32346,13,073,00348865,0500000US13073,13073,Columbia,06,751323672,45373097,"POLYGON ((-82.42533 33.65063, -82.30825 33.700...",13,30907
32347,13,073,00348865,0500000US13073,13073,Columbia,06,751323672,45373097,"POLYGON ((-82.42533 33.65063, -82.30825 33.700...",13,309HH